const ru = {
    title: 'Ear Gym',
    welcome: "Добро пожаловать в Ear Gym!",
    welcome2: "Здесь вы можете тренировать свои уши",
    loading: "Загрузка",
    music: "Музыка",
    piano: "Фортепиано",
    drums: "Ударная установка",
    electricguitar: "Электрогитара",
    eqplus: "Эквалайзер усиление",
    eqplusdesc: "Нужно услышать какая частота была усилена",
    eqminus: "Эквалайзер подавление",
    eqminusdesc: "Нужно услышать какая частота была подавлена",
    level: "Уровень",
    stage: "Этап",
    lives: "Жизни",
    hz: "Гц",
    db: "дБ",
    fxon: "Вкл",
    fxoff: "Выкл",
    gameOver: "Игра окончена",
    error: "Ошибка",
    gain: "gain",
    gaindesc: "gaindesc",
}
const en: typeof ru = {
    title: "Ear Gym",
    welcome: "Welcome to Ear Gym!",
    welcome2: "Here you can train you ears",
    loading: "Loading",
    music: "Music",
    piano: "Piano",
    drums: "Drum kit",
    electricguitar: "Electric guitar",
    eqplus: "Equalizer boost",
    eqplusdesc: "Find boosted frequency",
    eqminus: "Equalizer cut",
    eqminusdesc: "Find cut frequency",
    level: "Level",
    stage: "Stage",
    lives: "Lives",
    hz: "Hz",
    db: "dВ",
    fxon: "Fx on",
    fxoff: "Fx off",
    gameOver: "Game over",
    error: "Error",
    gain: "gain",
    gaindesc: "gaindesc",
}

const l = navigator.language === 'ru' ? ru : en;
export default l;